from setuptools import setup

setup(
    name="core",
    version="8.1.0",
    description="CORE Common Open Research Emulator (just the Python bits)",
    python_requires="==3.*,>=3.6.0",
    project_urls={
        "documentation": "https://coreemu.github.io/core/",
        "Source": "https://github.com/coreemu/core",
        "Bug Reports": "https://github.com/coreemu/core/issues",
    },
    author="Boeing Research and Technology",
    license="BSD-2-Clause",
    packages=[
        "core",
        "core.api",
        "core.api.grpc",
        "core.api.tlv",
        "core.configservice",
        "core.configservices",
        "core.configservices.frrservices",
        "core.configservices.nrlservices",
        "core.configservices.quaggaservices",
        "core.configservices.securityservices",
        "core.configservices.utilservices",
        "core.emane",
        "core.emane.models",
        "core.emulator",
        "core.gui",
        "core.gui.dialogs",
        "core.gui.frames",
        "core.gui.graph",
        "core.location",
        "core.nodes",
        "core.plugins",
        "core.services",
        "core.xml",
    ],
    package_dir={"": "."},
    package_data={
        "core": ["*.in"],
        "core.configservices.frrservices": [
            "templates/*.sh",
            "templates/usr/local/etc/frr/*.conf",
        ],
        "core.configservices.nrlservices": [
            "templates/*.mgen",
            "templates/*.sh",
            "templates/etc/olsrd/*.conf",
        ],
        "core.configservices.quaggaservices": [
            "templates/*.sh",
            "templates/usr/local/etc/quagga/*.conf",
        ],
        "core.configservices.securityservices": ["templates/*.sh"],
        "core.configservices.utilservices": [
            "templates/*.conf",
            "templates/*.sh",
            "templates/etc/apache2/*.conf",
            "templates/etc/dhcp/*.conf",
            "templates/etc/radvd/*.conf",
            "templates/var/www/*.html",
        ],
        "core.gui": [
            "data/backgrounds/*.gif",
            "data/backgrounds/*.jpg",
            "data/icons/*.gif",
            "data/icons/*.png",
            "data/mobility/*.scen",
            "data/xmls/*.xml",
        ],
    },
    install_requires=[
        "fabric",
        "grpcio",
        "invoke",
        "lxml",
        "mako",
        "netaddr",
        "pillow",
        "protobuf",
        "pyproj",
        "pyyaml",
    ],
    extras_require={
        "dev": [
            "black",
            "flake8",
            "grpcio-tools",
            "isort",
            "mock",
            "pre-commit",
            "pytest",
        ]
    },
    classifiers=[
        "Intended Audience :: Developers",
        "License :: OSI Approved :: BSD License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3 :: Only",
    ],
)
