# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/api/grpc/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ore/api/grpc/common.proto\x12\x06\x63ommon\"g\n\x0c\x43onfigOption\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0e\n\x06select\x18\x05 \x03(\t\x12\r\n\x05group\x18\x06 \x01(\t\"\x85\x01\n\x0cMappedConfig\x12\x30\n\x06\x63onfig\x18\x01 \x03(\x0b\x32 .common.MappedConfig.ConfigEntry\x1a\x43\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.common.ConfigOption:\x02\x38\x01\x62\x06proto3')



_CONFIGOPTION = DESCRIPTOR.message_types_by_name['ConfigOption']
_MAPPEDCONFIG = DESCRIPTOR.message_types_by_name['MappedConfig']
_MAPPEDCONFIG_CONFIGENTRY = _MAPPEDCONFIG.nested_types_by_name['ConfigEntry']
ConfigOption = _reflection.GeneratedProtocolMessageType('ConfigOption', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGOPTION,
  '__module__' : 'core.api.grpc.common_pb2'
  # @@protoc_insertion_point(class_scope:common.ConfigOption)
  })
_sym_db.RegisterMessage(ConfigOption)

MappedConfig = _reflection.GeneratedProtocolMessageType('MappedConfig', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAPPEDCONFIG_CONFIGENTRY,
    '__module__' : 'core.api.grpc.common_pb2'
    # @@protoc_insertion_point(class_scope:common.MappedConfig.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _MAPPEDCONFIG,
  '__module__' : 'core.api.grpc.common_pb2'
  # @@protoc_insertion_point(class_scope:common.MappedConfig)
  })
_sym_db.RegisterMessage(MappedConfig)
_sym_db.RegisterMessage(MappedConfig.ConfigEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPPEDCONFIG_CONFIGENTRY._options = None
  _MAPPEDCONFIG_CONFIGENTRY._serialized_options = b'8\001'
  _CONFIGOPTION._serialized_start=38
  _CONFIGOPTION._serialized_end=141
  _MAPPEDCONFIG._serialized_start=144
  _MAPPEDCONFIG._serialized_end=277
  _MAPPEDCONFIG_CONFIGENTRY._serialized_start=210
  _MAPPEDCONFIG_CONFIGENTRY._serialized_end=277
# @@protoc_insertion_point(module_scope)
