# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from core.api.grpc import configservices_pb2 as core_dot_api_dot_grpc_dot_configservices__pb2
from core.api.grpc import core_pb2 as core_dot_api_dot_grpc_dot_core__pb2
from core.api.grpc import emane_pb2 as core_dot_api_dot_grpc_dot_emane__pb2
from core.api.grpc import mobility_pb2 as core_dot_api_dot_grpc_dot_mobility__pb2
from core.api.grpc import services_pb2 as core_dot_api_dot_grpc_dot_services__pb2
from core.api.grpc import wlan_pb2 as core_dot_api_dot_grpc_dot_wlan__pb2


class CoreApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/core.CoreApi/StartSession',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.StartSessionResponse.FromString,
                )
        self.StopSession = channel.unary_unary(
                '/core.CoreApi/StopSession',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.StopSessionRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.StopSessionResponse.FromString,
                )
        self.CreateSession = channel.unary_unary(
                '/core.CoreApi/CreateSession',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.CreateSessionResponse.FromString,
                )
        self.DeleteSession = channel.unary_unary(
                '/core.CoreApi/DeleteSession',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteSessionResponse.FromString,
                )
        self.GetSessions = channel.unary_unary(
                '/core.CoreApi/GetSessions',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetSessionsRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetSessionsResponse.FromString,
                )
        self.GetSession = channel.unary_unary(
                '/core.CoreApi/GetSession',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetSessionResponse.FromString,
                )
        self.CheckSession = channel.unary_unary(
                '/core.CoreApi/CheckSession',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.CheckSessionRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.CheckSessionResponse.FromString,
                )
        self.SessionAlert = channel.unary_unary(
                '/core.CoreApi/SessionAlert',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.SessionAlertRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.SessionAlertResponse.FromString,
                )
        self.Events = channel.unary_stream(
                '/core.CoreApi/Events',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.EventsRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.Event.FromString,
                )
        self.Throughputs = channel.unary_stream(
                '/core.CoreApi/Throughputs',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.ThroughputsRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.ThroughputsEvent.FromString,
                )
        self.CpuUsage = channel.unary_stream(
                '/core.CoreApi/CpuUsage',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.CpuUsageRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.CpuUsageEvent.FromString,
                )
        self.AddNode = channel.unary_unary(
                '/core.CoreApi/AddNode',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.AddNodeRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.AddNodeResponse.FromString,
                )
        self.GetNode = channel.unary_unary(
                '/core.CoreApi/GetNode',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetNodeResponse.FromString,
                )
        self.EditNode = channel.unary_unary(
                '/core.CoreApi/EditNode',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.EditNodeRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.EditNodeResponse.FromString,
                )
        self.DeleteNode = channel.unary_unary(
                '/core.CoreApi/DeleteNode',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteNodeRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteNodeResponse.FromString,
                )
        self.NodeCommand = channel.unary_unary(
                '/core.CoreApi/NodeCommand',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.NodeCommandRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.NodeCommandResponse.FromString,
                )
        self.GetNodeTerminal = channel.unary_unary(
                '/core.CoreApi/GetNodeTerminal',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetNodeTerminalRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetNodeTerminalResponse.FromString,
                )
        self.MoveNode = channel.unary_unary(
                '/core.CoreApi/MoveNode',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.MoveNodeRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.MoveNodeResponse.FromString,
                )
        self.MoveNodes = channel.stream_unary(
                '/core.CoreApi/MoveNodes',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.MoveNodesRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.MoveNodesResponse.FromString,
                )
        self.AddLink = channel.unary_unary(
                '/core.CoreApi/AddLink',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.AddLinkRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.AddLinkResponse.FromString,
                )
        self.EditLink = channel.unary_unary(
                '/core.CoreApi/EditLink',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.EditLinkRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.EditLinkResponse.FromString,
                )
        self.DeleteLink = channel.unary_unary(
                '/core.CoreApi/DeleteLink',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteLinkRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteLinkResponse.FromString,
                )
        self.GetMobilityConfig = channel.unary_unary(
                '/core.CoreApi/GetMobilityConfig',
                request_serializer=core_dot_api_dot_grpc_dot_mobility__pb2.GetMobilityConfigRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_mobility__pb2.GetMobilityConfigResponse.FromString,
                )
        self.SetMobilityConfig = channel.unary_unary(
                '/core.CoreApi/SetMobilityConfig',
                request_serializer=core_dot_api_dot_grpc_dot_mobility__pb2.SetMobilityConfigRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_mobility__pb2.SetMobilityConfigResponse.FromString,
                )
        self.MobilityAction = channel.unary_unary(
                '/core.CoreApi/MobilityAction',
                request_serializer=core_dot_api_dot_grpc_dot_mobility__pb2.MobilityActionRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_mobility__pb2.MobilityActionResponse.FromString,
                )
        self.GetServiceDefaults = channel.unary_unary(
                '/core.CoreApi/GetServiceDefaults',
                request_serializer=core_dot_api_dot_grpc_dot_services__pb2.GetServiceDefaultsRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_services__pb2.GetServiceDefaultsResponse.FromString,
                )
        self.SetServiceDefaults = channel.unary_unary(
                '/core.CoreApi/SetServiceDefaults',
                request_serializer=core_dot_api_dot_grpc_dot_services__pb2.SetServiceDefaultsRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_services__pb2.SetServiceDefaultsResponse.FromString,
                )
        self.GetNodeService = channel.unary_unary(
                '/core.CoreApi/GetNodeService',
                request_serializer=core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceResponse.FromString,
                )
        self.GetNodeServiceFile = channel.unary_unary(
                '/core.CoreApi/GetNodeServiceFile',
                request_serializer=core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceFileRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceFileResponse.FromString,
                )
        self.ServiceAction = channel.unary_unary(
                '/core.CoreApi/ServiceAction',
                request_serializer=core_dot_api_dot_grpc_dot_services__pb2.ServiceActionRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_services__pb2.ServiceActionResponse.FromString,
                )
        self.GetConfigServiceDefaults = channel.unary_unary(
                '/core.CoreApi/GetConfigServiceDefaults',
                request_serializer=core_dot_api_dot_grpc_dot_configservices__pb2.GetConfigServiceDefaultsRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_configservices__pb2.GetConfigServiceDefaultsResponse.FromString,
                )
        self.GetNodeConfigService = channel.unary_unary(
                '/core.CoreApi/GetNodeConfigService',
                request_serializer=core_dot_api_dot_grpc_dot_configservices__pb2.GetNodeConfigServiceRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_configservices__pb2.GetNodeConfigServiceResponse.FromString,
                )
        self.ConfigServiceAction = channel.unary_unary(
                '/core.CoreApi/ConfigServiceAction',
                request_serializer=core_dot_api_dot_grpc_dot_services__pb2.ServiceActionRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_services__pb2.ServiceActionResponse.FromString,
                )
        self.GetWlanConfig = channel.unary_unary(
                '/core.CoreApi/GetWlanConfig',
                request_serializer=core_dot_api_dot_grpc_dot_wlan__pb2.GetWlanConfigRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_wlan__pb2.GetWlanConfigResponse.FromString,
                )
        self.SetWlanConfig = channel.unary_unary(
                '/core.CoreApi/SetWlanConfig',
                request_serializer=core_dot_api_dot_grpc_dot_wlan__pb2.SetWlanConfigRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_wlan__pb2.SetWlanConfigResponse.FromString,
                )
        self.WlanLink = channel.unary_unary(
                '/core.CoreApi/WlanLink',
                request_serializer=core_dot_api_dot_grpc_dot_wlan__pb2.WlanLinkRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_wlan__pb2.WlanLinkResponse.FromString,
                )
        self.GetEmaneModelConfig = channel.unary_unary(
                '/core.CoreApi/GetEmaneModelConfig',
                request_serializer=core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneModelConfigRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneModelConfigResponse.FromString,
                )
        self.SetEmaneModelConfig = channel.unary_unary(
                '/core.CoreApi/SetEmaneModelConfig',
                request_serializer=core_dot_api_dot_grpc_dot_emane__pb2.SetEmaneModelConfigRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_emane__pb2.SetEmaneModelConfigResponse.FromString,
                )
        self.GetEmaneEventChannel = channel.unary_unary(
                '/core.CoreApi/GetEmaneEventChannel',
                request_serializer=core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneEventChannelRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneEventChannelResponse.FromString,
                )
        self.EmanePathlosses = channel.stream_unary(
                '/core.CoreApi/EmanePathlosses',
                request_serializer=core_dot_api_dot_grpc_dot_emane__pb2.EmanePathlossesRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_emane__pb2.EmanePathlossesResponse.FromString,
                )
        self.EmaneLink = channel.unary_unary(
                '/core.CoreApi/EmaneLink',
                request_serializer=core_dot_api_dot_grpc_dot_emane__pb2.EmaneLinkRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_emane__pb2.EmaneLinkResponse.FromString,
                )
        self.SaveXml = channel.unary_unary(
                '/core.CoreApi/SaveXml',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.SaveXmlRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.SaveXmlResponse.FromString,
                )
        self.OpenXml = channel.unary_unary(
                '/core.CoreApi/OpenXml',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.OpenXmlRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.OpenXmlResponse.FromString,
                )
        self.GetInterfaces = channel.unary_unary(
                '/core.CoreApi/GetInterfaces',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetInterfacesRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetInterfacesResponse.FromString,
                )
        self.ExecuteScript = channel.unary_unary(
                '/core.CoreApi/ExecuteScript',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.ExecuteScriptRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.ExecuteScriptResponse.FromString,
                )
        self.GetConfig = channel.unary_unary(
                '/core.CoreApi/GetConfig',
                request_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetConfigResponse.FromString,
                )


class CoreApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartSession(self, request, context):
        """session rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Events(self, request, context):
        """streams
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Throughputs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CpuUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNode(self, request, context):
        """node rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveNodes(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLink(self, request, context):
        """link rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMobilityConfig(self, request, context):
        """mobility rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMobilityConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MobilityAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceDefaults(self, request, context):
        """service rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetServiceDefaults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeServiceFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServiceAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfigServiceDefaults(self, request, context):
        """config services
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeConfigService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigServiceAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWlanConfig(self, request, context):
        """wlan rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWlanConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WlanLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmaneModelConfig(self, request, context):
        """emane rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEmaneModelConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmaneEventChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmanePathlosses(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmaneLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveXml(self, request, context):
        """xml rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenXml(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterfaces(self, request, context):
        """utilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """globals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.StartSessionRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.StartSessionResponse.SerializeToString,
            ),
            'StopSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSession,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.StopSessionRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.StopSessionResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.CreateSessionRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.CreateSessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteSessionRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteSessionResponse.SerializeToString,
            ),
            'GetSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessions,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetSessionsRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetSessionsResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetSessionRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetSessionResponse.SerializeToString,
            ),
            'CheckSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSession,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.CheckSessionRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.CheckSessionResponse.SerializeToString,
            ),
            'SessionAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionAlert,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.SessionAlertRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.SessionAlertResponse.SerializeToString,
            ),
            'Events': grpc.unary_stream_rpc_method_handler(
                    servicer.Events,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.EventsRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.Event.SerializeToString,
            ),
            'Throughputs': grpc.unary_stream_rpc_method_handler(
                    servicer.Throughputs,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.ThroughputsRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.ThroughputsEvent.SerializeToString,
            ),
            'CpuUsage': grpc.unary_stream_rpc_method_handler(
                    servicer.CpuUsage,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.CpuUsageRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.CpuUsageEvent.SerializeToString,
            ),
            'AddNode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNode,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.AddNodeRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.AddNodeResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetNodeRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetNodeResponse.SerializeToString,
            ),
            'EditNode': grpc.unary_unary_rpc_method_handler(
                    servicer.EditNode,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.EditNodeRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.EditNodeResponse.SerializeToString,
            ),
            'DeleteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNode,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteNodeRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteNodeResponse.SerializeToString,
            ),
            'NodeCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeCommand,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.NodeCommandRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.NodeCommandResponse.SerializeToString,
            ),
            'GetNodeTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeTerminal,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetNodeTerminalRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetNodeTerminalResponse.SerializeToString,
            ),
            'MoveNode': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveNode,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.MoveNodeRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.MoveNodeResponse.SerializeToString,
            ),
            'MoveNodes': grpc.stream_unary_rpc_method_handler(
                    servicer.MoveNodes,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.MoveNodesRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.MoveNodesResponse.SerializeToString,
            ),
            'AddLink': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLink,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.AddLinkRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.AddLinkResponse.SerializeToString,
            ),
            'EditLink': grpc.unary_unary_rpc_method_handler(
                    servicer.EditLink,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.EditLinkRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.EditLinkResponse.SerializeToString,
            ),
            'DeleteLink': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLink,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteLinkRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.DeleteLinkResponse.SerializeToString,
            ),
            'GetMobilityConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMobilityConfig,
                    request_deserializer=core_dot_api_dot_grpc_dot_mobility__pb2.GetMobilityConfigRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_mobility__pb2.GetMobilityConfigResponse.SerializeToString,
            ),
            'SetMobilityConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMobilityConfig,
                    request_deserializer=core_dot_api_dot_grpc_dot_mobility__pb2.SetMobilityConfigRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_mobility__pb2.SetMobilityConfigResponse.SerializeToString,
            ),
            'MobilityAction': grpc.unary_unary_rpc_method_handler(
                    servicer.MobilityAction,
                    request_deserializer=core_dot_api_dot_grpc_dot_mobility__pb2.MobilityActionRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_mobility__pb2.MobilityActionResponse.SerializeToString,
            ),
            'GetServiceDefaults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceDefaults,
                    request_deserializer=core_dot_api_dot_grpc_dot_services__pb2.GetServiceDefaultsRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_services__pb2.GetServiceDefaultsResponse.SerializeToString,
            ),
            'SetServiceDefaults': grpc.unary_unary_rpc_method_handler(
                    servicer.SetServiceDefaults,
                    request_deserializer=core_dot_api_dot_grpc_dot_services__pb2.SetServiceDefaultsRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_services__pb2.SetServiceDefaultsResponse.SerializeToString,
            ),
            'GetNodeService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeService,
                    request_deserializer=core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceResponse.SerializeToString,
            ),
            'GetNodeServiceFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeServiceFile,
                    request_deserializer=core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceFileRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceFileResponse.SerializeToString,
            ),
            'ServiceAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ServiceAction,
                    request_deserializer=core_dot_api_dot_grpc_dot_services__pb2.ServiceActionRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_services__pb2.ServiceActionResponse.SerializeToString,
            ),
            'GetConfigServiceDefaults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfigServiceDefaults,
                    request_deserializer=core_dot_api_dot_grpc_dot_configservices__pb2.GetConfigServiceDefaultsRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_configservices__pb2.GetConfigServiceDefaultsResponse.SerializeToString,
            ),
            'GetNodeConfigService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeConfigService,
                    request_deserializer=core_dot_api_dot_grpc_dot_configservices__pb2.GetNodeConfigServiceRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_configservices__pb2.GetNodeConfigServiceResponse.SerializeToString,
            ),
            'ConfigServiceAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigServiceAction,
                    request_deserializer=core_dot_api_dot_grpc_dot_services__pb2.ServiceActionRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_services__pb2.ServiceActionResponse.SerializeToString,
            ),
            'GetWlanConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWlanConfig,
                    request_deserializer=core_dot_api_dot_grpc_dot_wlan__pb2.GetWlanConfigRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_wlan__pb2.GetWlanConfigResponse.SerializeToString,
            ),
            'SetWlanConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWlanConfig,
                    request_deserializer=core_dot_api_dot_grpc_dot_wlan__pb2.SetWlanConfigRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_wlan__pb2.SetWlanConfigResponse.SerializeToString,
            ),
            'WlanLink': grpc.unary_unary_rpc_method_handler(
                    servicer.WlanLink,
                    request_deserializer=core_dot_api_dot_grpc_dot_wlan__pb2.WlanLinkRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_wlan__pb2.WlanLinkResponse.SerializeToString,
            ),
            'GetEmaneModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmaneModelConfig,
                    request_deserializer=core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneModelConfigRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneModelConfigResponse.SerializeToString,
            ),
            'SetEmaneModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEmaneModelConfig,
                    request_deserializer=core_dot_api_dot_grpc_dot_emane__pb2.SetEmaneModelConfigRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_emane__pb2.SetEmaneModelConfigResponse.SerializeToString,
            ),
            'GetEmaneEventChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmaneEventChannel,
                    request_deserializer=core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneEventChannelRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneEventChannelResponse.SerializeToString,
            ),
            'EmanePathlosses': grpc.stream_unary_rpc_method_handler(
                    servicer.EmanePathlosses,
                    request_deserializer=core_dot_api_dot_grpc_dot_emane__pb2.EmanePathlossesRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_emane__pb2.EmanePathlossesResponse.SerializeToString,
            ),
            'EmaneLink': grpc.unary_unary_rpc_method_handler(
                    servicer.EmaneLink,
                    request_deserializer=core_dot_api_dot_grpc_dot_emane__pb2.EmaneLinkRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_emane__pb2.EmaneLinkResponse.SerializeToString,
            ),
            'SaveXml': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveXml,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.SaveXmlRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.SaveXmlResponse.SerializeToString,
            ),
            'OpenXml': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenXml,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.OpenXmlRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.OpenXmlResponse.SerializeToString,
            ),
            'GetInterfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterfaces,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetInterfacesRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetInterfacesResponse.SerializeToString,
            ),
            'ExecuteScript': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScript,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.ExecuteScriptRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.ExecuteScriptResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=core_dot_api_dot_grpc_dot_core__pb2.GetConfigRequest.FromString,
                    response_serializer=core_dot_api_dot_grpc_dot_core__pb2.GetConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.CoreApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoreApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/StartSession',
            core_dot_api_dot_grpc_dot_core__pb2.StartSessionRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.StartSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/StopSession',
            core_dot_api_dot_grpc_dot_core__pb2.StopSessionRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.StopSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/CreateSession',
            core_dot_api_dot_grpc_dot_core__pb2.CreateSessionRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.CreateSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/DeleteSession',
            core_dot_api_dot_grpc_dot_core__pb2.DeleteSessionRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.DeleteSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetSessions',
            core_dot_api_dot_grpc_dot_core__pb2.GetSessionsRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.GetSessionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetSession',
            core_dot_api_dot_grpc_dot_core__pb2.GetSessionRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.GetSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/CheckSession',
            core_dot_api_dot_grpc_dot_core__pb2.CheckSessionRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.CheckSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SessionAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/SessionAlert',
            core_dot_api_dot_grpc_dot_core__pb2.SessionAlertRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.SessionAlertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Events(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/core.CoreApi/Events',
            core_dot_api_dot_grpc_dot_core__pb2.EventsRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Throughputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/core.CoreApi/Throughputs',
            core_dot_api_dot_grpc_dot_core__pb2.ThroughputsRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.ThroughputsEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CpuUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/core.CoreApi/CpuUsage',
            core_dot_api_dot_grpc_dot_core__pb2.CpuUsageRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.CpuUsageEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/AddNode',
            core_dot_api_dot_grpc_dot_core__pb2.AddNodeRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.AddNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetNode',
            core_dot_api_dot_grpc_dot_core__pb2.GetNodeRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.GetNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/EditNode',
            core_dot_api_dot_grpc_dot_core__pb2.EditNodeRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.EditNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/DeleteNode',
            core_dot_api_dot_grpc_dot_core__pb2.DeleteNodeRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.DeleteNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NodeCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/NodeCommand',
            core_dot_api_dot_grpc_dot_core__pb2.NodeCommandRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.NodeCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNodeTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetNodeTerminal',
            core_dot_api_dot_grpc_dot_core__pb2.GetNodeTerminalRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.GetNodeTerminalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/MoveNode',
            core_dot_api_dot_grpc_dot_core__pb2.MoveNodeRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.MoveNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveNodes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/core.CoreApi/MoveNodes',
            core_dot_api_dot_grpc_dot_core__pb2.MoveNodesRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.MoveNodesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/AddLink',
            core_dot_api_dot_grpc_dot_core__pb2.AddLinkRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.AddLinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/EditLink',
            core_dot_api_dot_grpc_dot_core__pb2.EditLinkRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.EditLinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/DeleteLink',
            core_dot_api_dot_grpc_dot_core__pb2.DeleteLinkRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.DeleteLinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMobilityConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetMobilityConfig',
            core_dot_api_dot_grpc_dot_mobility__pb2.GetMobilityConfigRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_mobility__pb2.GetMobilityConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMobilityConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/SetMobilityConfig',
            core_dot_api_dot_grpc_dot_mobility__pb2.SetMobilityConfigRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_mobility__pb2.SetMobilityConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MobilityAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/MobilityAction',
            core_dot_api_dot_grpc_dot_mobility__pb2.MobilityActionRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_mobility__pb2.MobilityActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServiceDefaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetServiceDefaults',
            core_dot_api_dot_grpc_dot_services__pb2.GetServiceDefaultsRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_services__pb2.GetServiceDefaultsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetServiceDefaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/SetServiceDefaults',
            core_dot_api_dot_grpc_dot_services__pb2.SetServiceDefaultsRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_services__pb2.SetServiceDefaultsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNodeService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetNodeService',
            core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNodeServiceFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetNodeServiceFile',
            core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceFileRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_services__pb2.GetNodeServiceFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServiceAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/ServiceAction',
            core_dot_api_dot_grpc_dot_services__pb2.ServiceActionRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_services__pb2.ServiceActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfigServiceDefaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetConfigServiceDefaults',
            core_dot_api_dot_grpc_dot_configservices__pb2.GetConfigServiceDefaultsRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_configservices__pb2.GetConfigServiceDefaultsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNodeConfigService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetNodeConfigService',
            core_dot_api_dot_grpc_dot_configservices__pb2.GetNodeConfigServiceRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_configservices__pb2.GetNodeConfigServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigServiceAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/ConfigServiceAction',
            core_dot_api_dot_grpc_dot_services__pb2.ServiceActionRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_services__pb2.ServiceActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWlanConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetWlanConfig',
            core_dot_api_dot_grpc_dot_wlan__pb2.GetWlanConfigRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_wlan__pb2.GetWlanConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetWlanConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/SetWlanConfig',
            core_dot_api_dot_grpc_dot_wlan__pb2.SetWlanConfigRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_wlan__pb2.SetWlanConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WlanLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/WlanLink',
            core_dot_api_dot_grpc_dot_wlan__pb2.WlanLinkRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_wlan__pb2.WlanLinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEmaneModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetEmaneModelConfig',
            core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneModelConfigRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneModelConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetEmaneModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/SetEmaneModelConfig',
            core_dot_api_dot_grpc_dot_emane__pb2.SetEmaneModelConfigRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_emane__pb2.SetEmaneModelConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEmaneEventChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetEmaneEventChannel',
            core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneEventChannelRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_emane__pb2.GetEmaneEventChannelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EmanePathlosses(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/core.CoreApi/EmanePathlosses',
            core_dot_api_dot_grpc_dot_emane__pb2.EmanePathlossesRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_emane__pb2.EmanePathlossesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EmaneLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/EmaneLink',
            core_dot_api_dot_grpc_dot_emane__pb2.EmaneLinkRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_emane__pb2.EmaneLinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveXml(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/SaveXml',
            core_dot_api_dot_grpc_dot_core__pb2.SaveXmlRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.SaveXmlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenXml(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/OpenXml',
            core_dot_api_dot_grpc_dot_core__pb2.OpenXmlRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.OpenXmlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInterfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetInterfaces',
            core_dot_api_dot_grpc_dot_core__pb2.GetInterfacesRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.GetInterfacesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/ExecuteScript',
            core_dot_api_dot_grpc_dot_core__pb2.ExecuteScriptRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.ExecuteScriptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.CoreApi/GetConfig',
            core_dot_api_dot_grpc_dot_core__pb2.GetConfigRequest.SerializeToString,
            core_dot_api_dot_grpc_dot_core__pb2.GetConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
