# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/api/grpc/mobility.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.api.grpc import common_pb2 as core_dot_api_dot_grpc_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ore/api/grpc/mobility.proto\x12\x08mobility\x1a\x1a\x63ore/api/grpc/common.proto\"8\n\x0eMobilityAction\"&\n\x04\x45num\x12\t\n\x05START\x10\x00\x12\t\n\x05PAUSE\x10\x01\x12\x08\n\x04STOP\x10\x02\"\x86\x01\n\x0eMobilityConfig\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x34\n\x06\x63onfig\x18\x02 \x03(\x0b\x32$.mobility.MobilityConfig.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"?\n\x18GetMobilityConfigRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\"\xa1\x01\n\x19GetMobilityConfigResponse\x12?\n\x06\x63onfig\x18\x01 \x03(\x0b\x32/.mobility.GetMobilityConfigResponse.ConfigEntry\x1a\x43\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.common.ConfigOption:\x02\x38\x01\"a\n\x18SetMobilityConfigRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x31\n\x0fmobility_config\x18\x02 \x01(\x0b\x32\x18.mobility.MobilityConfig\"+\n\x19SetMobilityConfigResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"k\n\x15MobilityActionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12-\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x1d.mobility.MobilityAction.Enum\"(\n\x16MobilityActionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x62\x06proto3')



_MOBILITYACTION = DESCRIPTOR.message_types_by_name['MobilityAction']
_MOBILITYCONFIG = DESCRIPTOR.message_types_by_name['MobilityConfig']
_MOBILITYCONFIG_CONFIGENTRY = _MOBILITYCONFIG.nested_types_by_name['ConfigEntry']
_GETMOBILITYCONFIGREQUEST = DESCRIPTOR.message_types_by_name['GetMobilityConfigRequest']
_GETMOBILITYCONFIGRESPONSE = DESCRIPTOR.message_types_by_name['GetMobilityConfigResponse']
_GETMOBILITYCONFIGRESPONSE_CONFIGENTRY = _GETMOBILITYCONFIGRESPONSE.nested_types_by_name['ConfigEntry']
_SETMOBILITYCONFIGREQUEST = DESCRIPTOR.message_types_by_name['SetMobilityConfigRequest']
_SETMOBILITYCONFIGRESPONSE = DESCRIPTOR.message_types_by_name['SetMobilityConfigResponse']
_MOBILITYACTIONREQUEST = DESCRIPTOR.message_types_by_name['MobilityActionRequest']
_MOBILITYACTIONRESPONSE = DESCRIPTOR.message_types_by_name['MobilityActionResponse']
_MOBILITYACTION_ENUM = _MOBILITYACTION.enum_types_by_name['Enum']
MobilityAction = _reflection.GeneratedProtocolMessageType('MobilityAction', (_message.Message,), {
  'DESCRIPTOR' : _MOBILITYACTION,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.MobilityAction)
  })
_sym_db.RegisterMessage(MobilityAction)

MobilityConfig = _reflection.GeneratedProtocolMessageType('MobilityConfig', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _MOBILITYCONFIG_CONFIGENTRY,
    '__module__' : 'core.api.grpc.mobility_pb2'
    # @@protoc_insertion_point(class_scope:mobility.MobilityConfig.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _MOBILITYCONFIG,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.MobilityConfig)
  })
_sym_db.RegisterMessage(MobilityConfig)
_sym_db.RegisterMessage(MobilityConfig.ConfigEntry)

GetMobilityConfigRequest = _reflection.GeneratedProtocolMessageType('GetMobilityConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMOBILITYCONFIGREQUEST,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.GetMobilityConfigRequest)
  })
_sym_db.RegisterMessage(GetMobilityConfigRequest)

GetMobilityConfigResponse = _reflection.GeneratedProtocolMessageType('GetMobilityConfigResponse', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETMOBILITYCONFIGRESPONSE_CONFIGENTRY,
    '__module__' : 'core.api.grpc.mobility_pb2'
    # @@protoc_insertion_point(class_scope:mobility.GetMobilityConfigResponse.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _GETMOBILITYCONFIGRESPONSE,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.GetMobilityConfigResponse)
  })
_sym_db.RegisterMessage(GetMobilityConfigResponse)
_sym_db.RegisterMessage(GetMobilityConfigResponse.ConfigEntry)

SetMobilityConfigRequest = _reflection.GeneratedProtocolMessageType('SetMobilityConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETMOBILITYCONFIGREQUEST,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.SetMobilityConfigRequest)
  })
_sym_db.RegisterMessage(SetMobilityConfigRequest)

SetMobilityConfigResponse = _reflection.GeneratedProtocolMessageType('SetMobilityConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETMOBILITYCONFIGRESPONSE,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.SetMobilityConfigResponse)
  })
_sym_db.RegisterMessage(SetMobilityConfigResponse)

MobilityActionRequest = _reflection.GeneratedProtocolMessageType('MobilityActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOBILITYACTIONREQUEST,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.MobilityActionRequest)
  })
_sym_db.RegisterMessage(MobilityActionRequest)

MobilityActionResponse = _reflection.GeneratedProtocolMessageType('MobilityActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOBILITYACTIONRESPONSE,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.MobilityActionResponse)
  })
_sym_db.RegisterMessage(MobilityActionResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOBILITYCONFIG_CONFIGENTRY._options = None
  _MOBILITYCONFIG_CONFIGENTRY._serialized_options = b'8\001'
  _GETMOBILITYCONFIGRESPONSE_CONFIGENTRY._options = None
  _GETMOBILITYCONFIGRESPONSE_CONFIGENTRY._serialized_options = b'8\001'
  _MOBILITYACTION._serialized_start=70
  _MOBILITYACTION._serialized_end=126
  _MOBILITYACTION_ENUM._serialized_start=88
  _MOBILITYACTION_ENUM._serialized_end=126
  _MOBILITYCONFIG._serialized_start=129
  _MOBILITYCONFIG._serialized_end=263
  _MOBILITYCONFIG_CONFIGENTRY._serialized_start=218
  _MOBILITYCONFIG_CONFIGENTRY._serialized_end=263
  _GETMOBILITYCONFIGREQUEST._serialized_start=265
  _GETMOBILITYCONFIGREQUEST._serialized_end=328
  _GETMOBILITYCONFIGRESPONSE._serialized_start=331
  _GETMOBILITYCONFIGRESPONSE._serialized_end=492
  _GETMOBILITYCONFIGRESPONSE_CONFIGENTRY._serialized_start=425
  _GETMOBILITYCONFIGRESPONSE_CONFIGENTRY._serialized_end=492
  _SETMOBILITYCONFIGREQUEST._serialized_start=494
  _SETMOBILITYCONFIGREQUEST._serialized_end=591
  _SETMOBILITYCONFIGRESPONSE._serialized_start=593
  _SETMOBILITYCONFIGRESPONSE._serialized_end=636
  _MOBILITYACTIONREQUEST._serialized_start=638
  _MOBILITYACTIONREQUEST._serialized_end=745
  _MOBILITYACTIONRESPONSE._serialized_start=747
  _MOBILITYACTIONRESPONSE._serialized_end=787
# @@protoc_insertion_point(module_scope)
